### ISSUE TITLE
Rubric and Summary

### ISSUE THREAD

**Issue by ulisigi** [alvarezskinner/jammming#4]
### Criteria 1: App Creation, Folder Structure, and File Paths
* _Score Level:_ 4/4
* _Comment(s):_ Learner did make a CRA app and all components are properly located inside folders, file paths work
 
### Criteria 2: Correct Implementation of User Flows (e.g. Searching, Token Generation, Save Playlist, etc.)
* _Score Level:_ 3/4
* _Comment(s):_ •Search call triggers search method. 
•Spotify registers the app and grants an access token. 
•Search method returns tracks 
•Playlist saves to Spotify 
•Default playlist name changes back to New Playlist
•Learner uses local storage.
 
### Criteria 3: Proper JavaScript and JSX Syntax and Formatting
* _Score Level:_ 4/4
* _Comment(s):_ •Class was always changed to className
•HTML was converted to JSX
•Reset.css was added properly
•addTrack and removeTrack are written simply and not convoluted.
•A key was added to each track.  
 
### Criteria 4: Implementation Adheres to DRY Principles
* _Score Level:_ 4/4
* _Comment(s):_ Many of the URLs used in Spotify.js are saved as variables, as are the headers. Code uses map and filter. addTrack and removeTrack are written simply and not convoluted.
 
### Overall Score: 15/16
Your project Exceeds Expectations - great job! One thing I noticed when adding tracks to the playlist is that when titles or artist information spans multiple lines it can cause the text to expand beyond the fields:
![image](https://user-images.githubusercontent.com/26392454/52246809-3b43c700-28b5-11e9-9650-e8bba8b0ebfa.png)
For extra practice of the material needed to build this app, see if you can add code to run search by pressing the enter key. Keep up the excellent work, and happy coding!

**Comment by alvarezskinner** [comment]
May i know what is it that made it a 3/4 on the 2nd Criteria? Does it have to do with the track name being long?

**Comment by ulisigi** [comment]
Good evening. Yes, that bit that I shared in the screenshot was part of it. I included 6 of the 8 points from the scoring rubric for that 2nd Criteria in the summary above, although I probably should have left off "Default playlist name changes back to New Playlist." This didn't happen with your app after I saved a new playlist to a Spotify account, but only when I reloaded the app.
Here's the full scoring for the 2nd Criteria from our rubric:
```
8/8 possible levels
•Search call triggers search method. 
•Spotify registers the app and grants an access token. •Search method returns tracks 
•Playlist saves to Spotify •Default playlist name changes back to New Playlist
•Learner refactored Spotify.js in a way that shows deeper understanding
•Learner added code that runs search using enter key •Learner uses local storage.
```
Hope this helps. Happy coding!

**Comment by alvarezskinner** [comment]
Does indeed, Thanks for the clarification!
